from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPen, QColor, QPainter


class PaintLabel(QtWidgets.QLabel):
    def __init__(self, parent=None):
        QtWidgets.QOpenGLWidget.__init__(self, parent)
        self.lines = []

    def paintEvent(self, event):
        pen = QPen()
        pen.setWidth(2)
        pen.setColor(QColor(255, 100, 100))
        p = QPainter(self)
        p.setPen(pen)
        for l in self.lines:
            p.drawLine(l[0], l[1], l[2], l[3])


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 865)
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.setStyleSheet("background-color: rgb(202, 76, 78)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = PaintLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 864))
        self.label.setStyleSheet("background-image: url(map.png);")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 110, 371, 567))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.btn_city1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_city1.setFont(font)
        self.btn_city1.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_city1.setObjectName("btn_city2")
        self.horizontalLayout.addWidget(self.btn_city1)
        self.horizontalLayout.addWidget(self.label_3)
        self.city1 = QtWidgets.QComboBox(self.layoutWidget)
        self.city1.setMinimumSize(QtCore.QSize(180, 0))
        self.city1.setStyleSheet("color: rgb(255, 255, 255);")
        self.city1.setObjectName("city1")
        self.horizontalLayout.addWidget(self.city1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.btn_city2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_city2.setFont(font)
        self.btn_city2.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_city2.setObjectName("btn_city1")
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.btn_city2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.city2 = QtWidgets.QComboBox(self.layoutWidget)
        self.city2.setMinimumSize(QtCore.QSize(180, 0))
        self.city2.setStyleSheet("color: rgb(255, 255, 255);")
        self.city2.setObjectName("city2")
        self.horizontalLayout_2.addWidget(self.city2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)

        self.btn_show_map = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_show_map.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_show_map.setFont(font)
        self.btn_show_map.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_show_map.setObjectName("btn_route")
        self.horizontalLayout_3.addWidget(self.btn_show_map)

        self.btn_route = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_route.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_route.setFont(font)
        self.btn_route.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_route.setObjectName("btn_route")
        self.horizontalLayout_3.addWidget(self.btn_route)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.distance = QtWidgets.QLabel(self.layoutWidget)
        self.distance.setMinimumSize(QtCore.QSize(112, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.distance.setFont(font)
        self.distance.setStyleSheet("color: rgb(255, 255, 255);")
        self.distance.setObjectName("distance")
        self.horizontalLayout_4.addWidget(self.distance)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.path = QtWidgets.QLabel(self.layoutWidget)
        self.path.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.path.setFont(font)
        self.path.setStyleSheet("color: rgb(255, 255, 255);")
        self.path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.path.setObjectName("path")
        self.verticalLayout_3.addWidget(self.path)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.cities = []
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(510, 740, 369, 30))
        self.btn_close.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_close.setObjectName("btn_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        self.translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(self.translate("MainWindow", "MainWindow"))
        self.label_2.setText(self.translate("MainWindow", "Welcome to Palestine"))
        self.label_3.setText(self.translate("MainWindow", "City 1"))
        self.label_4.setText(self.translate("MainWindow", "City 2"))
        self.btn_route.setText(self.translate("MainWindow", "Show Route"))
        self.btn_show_map.setText(self.translate("MainWindow", "Show Cities"))
        self.btn_city1.setText(self.translate("MainWindow", "Mouse Choose"))
        self.btn_city2.setText(self.translate("MainWindow", "Mouse Choose"))
        self.label_5.setText(self.translate("MainWindow", "Distance:"))
        self.distance.setText(self.translate("MainWindow", "00"))
        self.label_9.setText(self.translate("MainWindow", "KM"))
        self.label_7.setText(self.translate("MainWindow", "Path:"))
        self.path.setText(self.translate("MainWindow", "x > y > z"))
        self.btn_close.setText(self.translate("MainWindow", "Close App"))
